---
title: "Meyer&Schmid_GhanaBats_RScript"
author: "MM & DS"
output: html_document
---

```{r}
library(vegan)
library(dplyr)
library(ggplot2)
library(lme4)
library(ggeffects)
library(DHARMa)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(devtools)
library(tibble)
library(picante)
library(gridExtra)
library(nlme)
library(lmerTest)
library(ggrepel)
library(ape)
library(RColorBrewer)
library(reshape2)
library(patchwork)
library(AER)
library(effects)
library(survey)
library(sjmisc)
library(MuMIn)
library(sjPlot)
library(sjstats)
library(car)
library(emmeans)
library(performance)
library(magrittr)
library(forcats)
library(plyr)
library(readxl)

metadata_common.species<-subset(Meyer_Schmid_Dataset_GhanaBats, Species!="Rousettus aegyptiacus")
str(metadata_common.species)
```

```{r}
###Prevalences

Meyer_Schmid_Dataset_GhanaBats$X229ELogical<-ifelse(Meyer_Schmid_Dataset_GhanaBats$X229ELogical>0,1,0)
prev_229E<-ddply(Meyer_Schmid_Dataset_GhanaBats, c("sample_period","site"), summarise,
                      pos = sum(na.omit(X229ELogical)), 
                      total=length(na.omit(X229ELogical)), 
                      prevalence=pos/total*100)

Meyer_Schmid_Dataset_GhanaBats$X2bLogical<-ifelse(Meyer_Schmid_Dataset_GhanaBats$X2bLogical>0,1,0)
prev_2b<-ddply(Meyer_Schmid_Dataset_GhanaBats, c("sample_period","site"), summarise,
                      pos = sum(na.omit(X2bLogical)), 
                      total=length(na.omit(X2bLogical)), 
                      prevalence=pos/total*100)

Meyer_Schmid_Dataset_GhanaBats$X2bBasalLogical<-ifelse(Meyer_Schmid_Dataset_GhanaBats$X2bBasalLogical>0,1,0)
prev_2bBasal<-ddply(Meyer_Schmid_Dataset_GhanaBats, c("sample_period","site"), summarise,
                      pos = sum(na.omit(X2bBasalLogical)), 
                      total=length(na.omit(X2bBasalLogical)), 
                      prevalence=pos/total*100)

Meyer_Schmid_Dataset_GhanaBats$BetaCLogical<-ifelse(Meyer_Schmid_Dataset_GhanaBats$BetaCLogical>0,1,0)
prev_2c<-ddply(Meyer_Schmid_Dataset_GhanaBats, c("sample_period","site"), summarise,
                      pos = sum(na.omit(BetaCLogical)), 
                      total=length(na.omit(BetaCLogical)), 
                      prevalence=pos/total*100)

```

```{r}

###Diversity Indices

diversity_spacetime <- dcast(Meyer_Schmid_Dataset_GhanaBats, Species ~sample_period*site , 
                   value.var = c("Species"))

sapply(diversity_spacetime, as.numeric)

str(diversity_spacetime)

div_mat<-as.matrix(diversity_spacetime[,2:56])

final_div_mat <- as.data.frame(t(div_mat))

final_div_mat = final_div_mat[-1,]

shannon<-diversity(final_div_mat, index = "shannon")
simpson<-diversity(final_div_mat, index = "inv")

SR<-specnumber(final_div_mat)

```

```{r}
###Correlations

#CoV 229E-like

Sha_229<-ggplot(data=Meyer_Schmid_Dataset_Correlation_GhanaBats, aes(SHA, CoV229))+
  ylim(-10,100)+
  xlim(0.4,1.7)+
  geom_smooth(method="lm", colour="black", size=1, fill="lightgrey")+
  geom_point(aes(shape=SITE, col=SITE), shape=19, size=5)+stat_cor(method="spearman", label.y.npc="top", label.x.npc = "middle", size=5)+ 
  ggtitle("alpha-CoV 229E-like")+
  theme_classic()+
  theme(legend.position = c("none")) +
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  ylab("Coronavirus Prevalence (%)")+
  xlab("Shannon Diversity Index") +
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))+
  annotate(geom="text", x=0.4, y=100, label="A",color="black", size=8)
Sha_229

Simp_229<-ggplot(data=Meyer_Schmid_Dataset_Correlation_GhanaBats, aes(INVSIMP, CoV229))+
  ylim(-10,100)+
  xlim(1.5,5)+
  geom_smooth(method="lm", colour="black", size=1, fill="lightgrey", linetype ="dashed")+
  geom_point(aes(shape=SITE, col=SITE), shape=19, size=5)+stat_cor(method="spearman", label.y.npc="top", label.x.npc = "middle", size=5)+ 
  ggtitle("alpha-CoV 229E-like")+
  theme_classic()+
  theme(legend.position = c("none")) +
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  ylab("Coronavirus Prevalence (%)")+
  xlab("Simpson Diversity Index") +
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))+
  annotate(geom="text", x=1.5, y=100, label="A",color="black", size=8)
Simp_229

SR_229<-ggplot(data=Meyer_Schmid_Dataset_Correlation_GhanaBats, aes(SR, CoV229))+
  ylim(-10,100)+
  xlim(2,8)+
  geom_smooth(method="lm", colour="black", size=1, fill="lightgrey", linetype ="dashed")+
  geom_point(aes(shape=SITE, col=SITE), shape=19, size=5)+stat_cor(method="spearman", label.y.npc="top", label.x.npc = "middle", size=5)+ 
  ggtitle("")+
  theme_classic()+
  theme(legend.position = c("none")) +
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  ylab("Coronavirus Prevalence (%)")+
  xlab("Species Richness") +
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))+
  annotate(geom="text", x=2, y=100, label="C",color="black", size=8)
SR_229

#CoV 2b

Sha_2b<-ggplot(data=Meyer_Schmid_Dataset_Correlation_GhanaBats, aes(SHA, CoV2b))+
 ylim(-10,100)+
  xlim(0.4,1.7)+
  geom_smooth(method="lm", colour="black", size=1, fill="lightgrey")+
  geom_point(aes(shape=SITE, col=SITE), shape=19, size=5)+stat_cor(method="spearman", label.y.npc="top", label.x.npc = "middle", size=5)+ 
  ggtitle("beta-CoV 2b")+
  scale_color_manual(labels = c("BUOYEM 1"= "Buoyem 1", "BUOYEM 2" = "Buoyem 2", "FORIKROM" = "Forikrom", "KWAMANG 1" = "Kwamang 1", "KWAMANG 2" = "Kwamang 2"), values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c(0.8, 0.7)) +
  ylab("")+
  xlab("Shannon Diversity Index") +
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"),legend.text=element_text(size=18), legend.title = element_blank())+
  annotate(geom="text", x=0.4, y=100, label="B",color="black", size=8)
Sha_2b

Simp_2b<-ggplot(data=Meyer_Schmid_Dataset_Correlation_GhanaBats, aes(INVSIMP, CoV2b))+
  ylim(-10,100)+
  xlim(1.5,5)+
  geom_smooth(method="lm", colour="black", size=1, fill="lightgrey")+
  geom_point(aes(shape=SITE, col=SITE), shape=19, size=5)+stat_cor(method="spearman", label.y.npc="top", label.x.npc = "middle", size=5)+ 
  ggtitle("beta-CoV 2b")+
  scale_color_manual(labels = c("BUOYEM 1" = "Buoyem 1", "BUOYEM 2" = "Buoyem 2", "FORIKROM" = "Forikrom", "KWAMANG 1" = "Kwamang 1", "KWAMANG 2" = "Kwamang 2"), values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c(0.85, 0.65)) +
  ylab("")+
  xlab("Simpson Diversity Index") +
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"), legend.text=element_text(size=18), axis.text.y=element_blank(), legend.title = element_blank())+
  annotate(geom="text", x=1.5, y=100, label="B",color="black", size=8)
Simp_2b

SR_2b<-ggplot(data=Meyer_Schmid_Dataset_Correlation_GhanaBats, aes(SR, CoV2b))+
  ylim(-10,100)+
  xlim(2,8)+
  geom_smooth(method="lm", colour="black", size=1, fill="lightgrey", linetype ="dashed")+
  geom_point(aes(shape=SITE, col=SITE), shape=19, size=5)+stat_cor(method="spearman", label.y.npc="top", label.x.npc = "middle", size=5)+ 
  ggtitle("")+
  theme_classic()+
  theme(legend.position = c("none")) +
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  ylab("")+
  xlab("Species Richness") +
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))+
  annotate(geom="text", x=2, y=100, label="D",color="black", size=8)
SR_2b

#Figures main text

Fig2<-grid.arrange(Sha_229, Sha_2b, ncol=2, nrow=1)
#export width: 1000, height=500

#Figures Supplmentary Material

FigS2<-grid.arrange(Simp_229, Simp_2b, SR_229 ,SR_2b, ncol=2, nrow=2)
#export width: 1000, height=1000

```


```{r}
###Community assemblage

#Species

Meyer_Schmid_Dataset_GhanaBats$Species <- factor(Meyer_Schmid_Dataset_GhanaBats$Species,levels = c("Coleura afra", "Hipposideros abae", "Macronycteris gigas", "Hipposideros jonesi", "Lissonycteris angolensis", "Nycteris macrotis",  "Rhinolophus landeri", "Rousettus aegyptiacus","Hipposideros caffer B", "Hipposideros caffer C","Hipposideros caffer D" ))

species_dist_colors<-c("Coleura afra"="#506a71",
                        "Hipposideros abae"="#e5c296",
                        "Hipposideros caffer B"="#bbc7ce",
                        "Hipposideros caffer C"="#dcdb71",
                        "Hipposideros caffer D"="#0b2a5f",
                        "Hipposideros jonesi"="#575314",
                        "Lissonycteris angolensis"="#3c82ac",
                        "Macronycteris gigas"="#9e4d2f",
                        "Nycteris macrotis"="#e4b142",
                        "Rhinolophus landeri"="#007483",
                        "Rousettus aegyptiacus"="#676b23")

labels <- c(BUO1 = "Buoyem 1", BUO2 = "Buoyem 2", FO = "Forikrom", KW1 = "Kwamang 1", KW2 = "Kwamang 2")

Meyer_Schmid_Dataset_GhanaBats$sample_month <- factor(Meyer_Schmid_Dataset_GhanaBats$sample_month,levels = c("Sep-Oct 2010", "Nov-Dec 2010", "Jan-Feb 2011", "Mar-Apr 2011",
            "May-Jun 2011", "Jul-Aug 2011", "Sep-Oct 2011", "Nov-Dec 2011",
            "Jan-Feb 2012", "Mar-Apr 2012", "May-Jun 2012", "Jul-Aug 2012"))

species<-ggplot(Meyer_Schmid_Dataset_GhanaBats, aes(x = sample_month, fill = Species)) +
    geom_bar(position = "fill") +
     ylab("Rel. Abundance of Species") + scale_fill_manual(values = species_dist_colors)+
  xlab("") +ggtitle("")+
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 25, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(face = "italic", size = 20),
        legend.position='none',
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        text = element_text(colour = "black", size=20),
        axis.text = element_text(colour = "black", size=11),
        #axis.text.x = element_text(size=16, angle=90, vjust = 0.5))+
        axis.text.x=element_blank())+
  facet_wrap(~site, ncol =5, labeller = labeller(site = labels))
species
#Fig1B export width: 1800 height: 500

#age

age_dist_colors<-c("Adult"="#7e365b","Subadult"="#DD7373")

subset_age1<-subset(Meyer_Schmid_Dataset_GhanaBats, age!="NA")

age<-ggplot(subset_age1, aes(x = sample_month, fill = age)) +
    geom_bar(position = "fill") +
     ylab("Rel. Abundance of Subadults")+  scale_fill_manual(values = age_dist_colors)+
  xlab("") +ggtitle("")+
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 25, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 20),
        legend.position='none',

        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        text = element_text(colour = "black", size=20),
        axis.text = element_text(colour = "black", size=11),
        #axis.text.x = element_text(size=16, angle=90, vjust = 0.5))+
        axis.text.x=element_blank())+
  facet_wrap(~site, ncol =5, labeller = labeller(site = labels))+
               theme(strip.text.x = element_blank())
age
#Fig1C export width: 1800 height: 480

#prevalences

longData<-gather(Meyer_Schmid_Dataset_Correlation_GhanaBats,CoV, value,CoV229:CoV2c,factor_key = T)

prev_dist_colors<-c("CoV229"="#E07A5F",
                   "CoV2b"="#1C5253",
                   "CoV2bBas"="#82A3A1",
                   "CoV2c"="#C3EB78")

longData$sample_month <- factor(longData$sample_month,levels = c("Sep-Oct2010", "Nov-Dec2010", "Jan-Feb2011", "Mar-Apr2011",
            "May-Jun2011", "Jul-Aug2011", "Sep-Oct2011", "Nov-Dec2011",
            "Jan-Feb2012", "Mar-Apr2012", "May-Jun2012", "Jul-Aug2012"))

prev<-ggplot(longData, aes(x = sample_month, y=value, colour = CoV, group=CoV, na.omit = TRUE))+
  geom_point(size=4)+
  geom_line(size=1.5) +
     ylab("Coronavirus Prevalence")+ scale_color_manual(labels = c("CoV229"="alpha-CoV 229E-like","CoV2b" = "beta-CoV 2b", "CoV2bBas" ="beta-CoV 2bBasal", "CoV2c" ="beta-CoV 2c"),values = prev_dist_colors)+
  xlab("") +ggtitle("")+
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 25, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 20),
        legend.position='none',
        axis.title.y = element_text(vjust= +2.5),
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        text = element_text(colour = "black", size=20),
        axis.text = element_text(colour = "black", size=11),
        axis.text.x = element_text(size=16, angle=90, vjust = 0.6))+
  facet_wrap(~SITE, ncol =5, labeller = labeller(site = labels))+
               theme(strip.text.x = element_blank())
prev
#Fig1D export width: 1800 height: 550

Fig1<-grid.arrange(species, age, prev, nrow=3)

```


```{r}
#####Modelling - Infection likelihood

#on individual level

subset_age<-subset(Meyer_Schmid_Dataset_GhanaBats, age!="NA")
subset_age$Species<-as.factor(subset_age$Species)

m229<-glm(X229ELogical ~ Species + age, data = subset_age, na.action=na.fail)
summary(m229)
tab_model(m229)

m2b<-glm(X2bLogical ~ Species + age, data = subset_age, na.action=na.fail)
summary(m2b)
tab_model(m2b)


#on individual level within Hipposideros genus


Hippo<-subset(subset_age, Genus == "Hipposideros")

m229<-glm(X229ELogical~ Species, data = Hippo, na.action=na.fail)
summary(m229)
tab_model(m229)

m2b<-glm(X2bLogical~ Species, data = Hippo, na.action=na.fail)
summary(m2b)
tab_model(m2b)


###CoV 229E-like

#full model

mod229<-glmer(X229ELogical~ SHA +SR +INVSIMP + RelAbundHipAb + RelAbundHipB + RelAbundHipC + RelAbundHipD + RelAbundColAf + RelAbundNyc + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)

#Collinearity among predictors
x<-check_collinearity(mod229)
plot(x)
#high multicollinearity!!!
#summary(mod229)
#tab_model(mod229)
#dredge(mod229)

###separate models:

##Shannon

mod229_r<-glmer(X229ELogical~ SHA + RelAbundHipAb + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229_r)
summary(mod229_r)
tab_model(mod229_r)
dredge_mod229_r<-dredge(mod229_r)
#summary(model.avg(dredge_mod229_r, subset = delta <= 2))

mod229_r2<-glmer(X229ELogical~ SHA + RelAbundHipB + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229_r2)
summary(mod229_r2)
tab_model(mod229_r2)
dredge_mod229_r2<-dredge(mod229_r2)
#summary(model.avg(dredge_mod229_r2, subset = delta <= 2))

mod229_r3<-glmer(X229ELogical~ SHA + RelAbundHipC + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229_r3)
summary(mod229_r3)
tab_model(mod229_r3)
dredge_mod229_r3<-dredge(mod229_r3)
#summary(model.avg(dredge_mod229_r3, subset = delta <= 2))

mod229_r4<-glmer(X229ELogical~ SHA + RelAbundHipD + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229_r4)
summary(mod229_r4)
tab_model(mod229_r4)
dredge_mod229_r4<-dredge(mod229_r4)
#summary(model.avg(dredge_mod229_r4, subset = delta <= 2))

mod229_r5<-glmer(X229ELogical~ SHA + RelAbundColAf + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229_r5)
summary(mod229_r5)
tab_model(mod229_r5)
dredge_mod229_r5<-dredge(mod229_r5)
#summary(model.avg(dredge_mod229_r5, subset = delta <= 2))

mod229_r6<-glmer(X229ELogical~ SHA + RelAbundNyc + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229_r6)
summary(mod229_r6)
tab_model(mod229_r6)
dredge_mod229_r6<-dredge(mod229_r6)
#summary(model.avg(dredge_mod229_r6, subset = delta <= 2))

#FDR correction
p_229_Sha<-c(0.027, 0.006, 0.014, 0.013, 0.094, 0.118)
p.adjust(p_229_Sha, method="fdr", n=length(p_229_Sha))

p_229_Abund<-c(0.917, 0.234, 0.007, 0.630, 0.262, 0.020)
p.adjust(p_229_Abund, method="fdr", n=length(p_229_Abund))

p_229_SA<-c(0.027, 0.020, 0.028, 0.022, 0.027, 0.057)
p.adjust(p_229_SA, method="fdr", n=length(p_229_SA))

#plots
dat.effects_r1 <- effect("SHA", mod = mod229_r3, xlevels = list(SHA = seq(.3, 1.8, length.out = 100)))
dat.effects_r1 <- as.data.frame(dat.effects_r1)

p_r1<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = SHA, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r1, aes(x = SHA, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r1, aes(x = SHA, y = fit), size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("Shannon Diversity Index")+
  ylab("Coronavirus Infection Probability") +
  ggtitle("alpha-CoV 229E-like")+
  annotate(geom="text", x=.35, y=.9, label="A", color="black", size =8)+
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r1

dat.effects_r3 <- effect("RelAbundHipAb", mod = mod229_r, xlevels = list(RelAbundHipAb = seq(0, 100, length.out = 100)))
dat.effects_r3 <- as.data.frame(dat.effects_r3)

p_r3<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipAb, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r3, aes(x = RelAbundHipAb, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r3, aes(x = RelAbundHipAb, y = fit), linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. abae")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=5, y=.75, label="C", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r3

dat.effects_r5 <- effect("RelAbundHipB", mod = mod229_r2, xlevels = list(RelAbundHipB = seq(0, 100, length.out = 100)))
dat.effects_r5 <- as.data.frame(dat.effects_r5)

p_r5<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipB, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r5, aes(x = RelAbundHipB, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r5, aes(x = RelAbundHipB, y = fit), linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. caffer B")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"), axis.text.y=element_blank())
p_r5

dat.effects_r7 <- effect("RelAbundHipC", mod = mod229_r3, xlevels = list(RelAbundHipC = seq(0, 100, length.out = 100)))
dat.effects_r7 <- as.data.frame(dat.effects_r7)

p_r7<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipC, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r7, aes(x = RelAbundHipC, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r7, aes(x = RelAbundHipC, y = fit), size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. caffer C")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r7

dat.effects_r9 <- effect("RelAbundHipD", mod = mod229_r4, xlevels = list(RelAbundHipD = seq(0, 100, length.out = 100)))
dat.effects_r9 <- as.data.frame(dat.effects_r9)

p_r9<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipD, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r9, aes(x = RelAbundHipD, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r9, aes(x = RelAbundHipD, y = fit), linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. caffer D")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"), axis.text.y=element_blank())
p_r9

dat.effects_r11 <- effect("RelAbundColAf", mod = mod229_r5, xlevels = list(RelAbundColAf = seq(0, 100, length.out = 100)))
dat.effects_r11 <- as.data.frame(dat.effects_r11)

p_r11<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundColAf, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r11, aes(x = RelAbundColAf, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r11, aes(x = RelAbundColAf, y = fit), linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("C. afra")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r11

dat.effects_r13 <- effect("RelAbundNyc", mod = mod229_r6, xlevels = list(RelAbundNyc = seq(0, 100, length.out = 100)))
dat.effects_r13 <- as.data.frame(dat.effects_r13)

p_r13<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundNyc, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r13, aes(x = RelAbundNyc, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r13, aes(x = RelAbundNyc, y = fit), linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("N. macrotis")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"), axis.text.y=element_blank())
p_r13


dat.effects_r15 <- effect("relative_subadults", mod = mod229_r3, xlevels = list(relative_subadults = seq(0, 100, length.out = 100)))
dat.effects_r15 <- as.data.frame(dat.effects_r15)

p_r15<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = relative_subadults, y = X229ELogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r15, aes(x = relative_subadults, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r15, aes(x = relative_subadults, y = fit), size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("Relative Abundance of Subadults")+
  ylab("Coronavirus Infection Probability") +
  ggtitle("")+
  annotate(geom="text", x=.3, y=.9, label="E", color="black", size =8)+
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r15

##Simpson

mod229Simp_r<-glmer(X229ELogical~ INVSIMP + RelAbundHipAb + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229Simp_r)
summary(mod229Simp_r)
tab_model(mod229Simp_r)
dredge_mod229Simp_r<-dredge(mod229Simp_r)
#summary(model.avg(dredge_mod229Simp_r, subset = delta <= 2))

mod229Simp_r2<-glmer(X229ELogical~ INVSIMP + RelAbundHipB + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229Simp_r2)
summary(mod229Simp_r2)
tab_model(mod229Simp_r2)
dredge_mod229Simp_r2<-dredge(mod229Simp_r2)
#summary(model.avg(dredge_mod229Simp_r2, subset = delta <= 2))

mod229Simp_r3<-glmer(X229ELogical~ INVSIMP + RelAbundHipC + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229Simp_r3)
summary(mod229Simp_r3)
tab_model(mod229Simp_r3)
dredge_mod229Simp_r3<-dredge(mod229Simp_r3)
#summary(model.avg(dredge_mod229Simp_r3, subset = delta <= 2))

mod229Simp_r4<-glmer(X229ELogical~ INVSIMP + RelAbundHipD + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229Simp_r4)
summary(mod229Simp_r4)
tab_model(mod229Simp_r4)
dredge_mod229Simp_r4<-dredge(mod229Simp_r4)
#summary(model.avg(dredge_mod229Simp_r4, subset = delta <= 2))

mod229Simp_r5<-glmer(X229ELogical~ INVSIMP + RelAbundColAf + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229Simp_r5)
summary(mod229Simp_r5)
tab_model(mod229Simp_r5)
dredge_mod229Simp_r5<-dredge(mod229Simp_r5)
#summary(model.avg(dredge_mod229Simp_r5, subset = delta <= 2))

mod229Simp_r6<-glmer(X229ELogical~ INVSIMP + RelAbundNyc + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229Simp_r6)
summary(mod229Simp_r6)
tab_model(mod229Simp_r6)
dredge_mod229Simp_r6<-dredge(mod229Simp_r6)
#summary(model.avg(dredge_mod229Simp_r6, subset = delta <= 2))

#FDR correction

p_229_Simp<-c(0.078, 0.022, 0.077, 0.043, 0.268, 0.213)
p.adjust(p_229_Simp, method="fdr", n=length(p_229_Simp))

p_229Simp_Abund<-c(0.615, 0.312, 0.013, 0.750, 0.218, 0.013)
p.adjust(p_229Simp_Abund, method="fdr", n=length(p_229Simp_Abund))

p_229Simp_SA<-c(0.031, 0.033, 0.037, 0.035, 0.034, 0.072)
p.adjust(p_229Simp_SA, method="fdr", n=length(p_229Simp_SA))

##Species Richness

mod229SR_r<-glmer(X229ELogical~ SR + RelAbundHipAb + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229SR_r)
summary(mod229SR_r)
tab_model(mod229SR_r)
dredge_mod229SR_r<-dredge(mod229SR_r)
#summary(model.avg(dredge_mod229SR_r, subset = delta <= 2))

mod229SR_r2<-glmer(X229ELogical~ SR + RelAbundHipB + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229SR_r2)
summary(mod229SR_r2)
tab_model(mod229SR_r2)
dredge_mod229SR_r2<-dredge(mod229SR_r2)
#summary(model.avg(dredge_mod229SR_r2, subset = delta <= 2))

mod229SR_r3<-glmer(X229ELogical~ SR + RelAbundHipC + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229SR_r3)
summary(mod229SR_r3)
tab_model(mod229SR_r3)
dredge_mod229SR_r3<-dredge(mod229SR_r3)
#summary(model.avg(dredge_mod229SR_r3, subset = delta <= 2))

mod229SR_r4<-glmer(X229ELogical~ SR + RelAbundHipD + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229SR_r4)
summary(mod229SR_r4)
tab_model(mod229SR_r4)
dredge_mod229SR_r4<-dredge(mod229SR_r4)
#summary(model.avg(dredge_mod229SR_r4, subset = delta <= 2))

mod229SR_r5<-glmer(X229ELogical~ SR + RelAbundColAf + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229SR_r5)
summary(mod229SR_r5)
tab_model(mod229SR_r5)
dredge_mod229SR_r5<-dredge(mod229SR_r5)
#summary(model.avg(dredge_mod229SR_r5, subset = delta <= 2))

mod229SR_r6<-glmer(X229ELogical~ SR + RelAbundNyc + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod229SR_r6)
summary(mod229SR_r6)
tab_model(mod229SR_r6)
dredge_mod229SR_r6<-dredge(mod229SR_r6)
#summary(model.avg(dredge_mod229SR_r6, subset = delta <= 2))

#FDR correction

p_229_SR<-c(0.090, 0.034, 0.039, 0.082, 0.123, 0.170)
p.adjust(p_229_SR, method="fdr", n=length(p_229_SR))

p_229SR_Abund<-c(0.747, 0.555, 0.006, 0.727, 0.097, 0.010)
p.adjust(p_229SR_Abund, method="fdr", n=length(p_229SR_Abund))

p_229SR_SA<-c(0.007, 0.006, 0.008, 0.041, 0.011, 0.031)
p.adjust(p_229SR_SA, method="fdr", n=length(p_229SR_SA))


### CoV 2b

#full model

mod2b<-glm(X2bLogical~ SHA + SR + INVSIMP +RelAbundHipAb + RelAbundHipB + RelAbundHipC + RelAbundHipD + RelAbundColAf + RelAbundNyc + relative_subadults, family = binomial, data = metadata_common.species, na.action=na.fail)
y<-check_collinearity(mod2b)
plot(y)
#high collinearity!
#summary(mod2b)
#tab_model(mod2b)
#dredge(mod2b)


#separate models:

##Shannon

mod2b_r<-glmer(X2bLogical~ SHA + RelAbundHipAb + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2b_r)
summary(mod2b_r)
tab_model(mod2b_r)
dredge_mod2b_r<-dredge(mod2b_r)
#summary(model.avg(dredge_mod2b_r, subset = delta <= 2))

mod2b_r2<-glmer(X2bLogical~ SHA + RelAbundHipB + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2b_r2)
summary(mod2b_r2)
tab_model(mod2b_r2)
dredge_mod2b_r2<-dredge(mod2b_r2)
#summary(model.avg(dredge_mod2b_r2, subset = delta <= 2))

mod2b_r3<-glmer(X2bLogical~ SHA + RelAbundHipC + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2b_r3)
summary(mod2b_r3)
tab_model(mod2b_r3)
dredge_mod2b_r3<-dredge(mod2b_r3)
#summary(model.avg(dredge_mod2b_r3, subset = delta <= 2))

mod2b_r4<-glmer(X2bLogical~ SHA + RelAbundHipD + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2b_r4)
summary(mod2b_r4)
tab_model(mod2b_r4)
dredge_mod2b_r4<-dredge(mod2b_r4)
#summary(model.avg(dredge_mod2b_r4, subset = delta <= 2))

mod2b_r5<-glmer(X2bLogical~ SHA + RelAbundColAf + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2b_r5)
summary(mod2b_r5)
tab_model(mod2b_r5)
dredge_mod2b_r5<-dredge(mod2b_r5)
#summary(model.avg(dredge_mod2b_r5, subset = delta <= 2))

mod2b_r6<-glmer(X2bLogical~ SHA + RelAbundNyc + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2b_r6)
summary(mod2b_r6)
tab_model(mod2b_r6)
dredge_mod2b_r6<-dredge(mod2b_r6)
#summary(model.avg(dredge_mod2b_r6, subset = delta <= 2))


#FDR correction

p_2b_Sha<-c(5.83e-09, 1.8e-05, 4.46e-07, 0.011, 1.84e-05, 3.25e-05)
p.adjust(p_2b_Sha, method="fdr", n=length(p_2b_Sha))

p_2b_Abund<-c(0.001, 0.512, 0.636, 9.24e-10, 0.866, 0.021)
p.adjust(p_2b_Abund, method="fdr", n=length(p_2b_Abund))

p_2b_SA<-c(0.001, 0.000298, 0.00022, 0.010, 0.000282, 0.000522)
p.adjust(p_2b_SA, method="fdr", n=length(p_2b_SA))

#plots

dat.effects_r2 <- effect("SHA", mod = mod2b_r4, xlevels = list(SHA = seq(.3, 1.8, length.out = 100)))
dat.effects_r2 <- as.data.frame(dat.effects_r2)

p_r2<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = SHA, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r2, aes(x = SHA, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r2, aes(x = SHA, y = fit), size=1) + 
  scale_color_manual(labels = c(BUO1 = "Buoyem 1", BUO2 = "Buoyem 2", FO = "Forikrom", KW1 = "Kwamang 1", KW2 = "Kwamang 2"), values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c(0.8, 0.45)) +
  xlab("Shannon Diversity Index")+
  ylab("") + 
  ggtitle("beta-CoV 2b")+
  annotate(geom="text", x=.3, y=.9, label="B", color="black", size =8)+
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), plot.title = element_text(hjust = 0.5, size=22, face="bold"), axis.text.y=element_blank(), legend.text=element_text(size=18), legend.title = element_blank())
p_r2

dat.effects_r4 <- effect("RelAbundHipAb", mod = mod2b_r, xlevels = list(RelAbundHipAb = seq(0, 100, length.out = 100)))
dat.effects_r4 <- as.data.frame(dat.effects_r4)

p_r4<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipAb, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r4, aes(x = RelAbundHipAb, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r4, aes(x = RelAbundHipAb, y = fit), size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. abae")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=5, y=.75, label="D", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r4

dat.effects_r6 <- effect("RelAbundHipB", mod = mod2b_r2, xlevels = list(RelAbundHipB = seq(0, 100, length.out = 100)))
dat.effects_r6 <- as.data.frame(dat.effects_r6)

p_r6<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipB, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r6, aes(x = RelAbundHipB, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r6, aes(x = RelAbundHipB, y = fit),linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. caffer B")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r6

dat.effects_r8 <- effect("RelAbundHipC", mod = mod2b_r3, xlevels = list(RelAbundHipC = seq(0, 100, length.out = 100)))
dat.effects_r8 <- as.data.frame(dat.effects_r8)

p_r8<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipC, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r8, aes(x = RelAbundHipC, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r8, aes(x = RelAbundHipC, y = fit),linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. caffer C")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r8

dat.effects_r10 <- effect("RelAbundHipD", mod = mod2b_r4, xlevels = list(RelAbundHipD = seq(0, 100, length.out = 100)))
dat.effects_r10 <- as.data.frame(dat.effects_r10)

p_r10<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundHipD, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r10, aes(x = RelAbundHipD, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r10, aes(x = RelAbundHipD, y = fit), size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("H. caffer D")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r10

dat.effects_r12 <- effect("RelAbundColAf", mod = mod2b_r5, xlevels = list(RelAbundColAf = seq(0, 100, length.out = 100)))
dat.effects_r12 <- as.data.frame(dat.effects_r12)

p_r12<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundColAf, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r12, aes(x = RelAbundColAf, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r12, aes(x = RelAbundColAf, y = fit),linetype="dashed", size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("C. afra")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r12

dat.effects_r14 <- effect("RelAbundNyc", mod = mod2b_r6, xlevels = list(RelAbundNyc = seq(0, 100, length.out = 100)))
dat.effects_r14 <- as.data.frame(dat.effects_r14)

p_r14<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = RelAbundNyc, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r14, aes(x = RelAbundNyc, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r14, aes(x = RelAbundNyc, y = fit), size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("N. macrotis")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="", color="black", size =8)+
  theme(axis.title=element_text(face="bold.italic", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r14

dat.effects_r16 <- effect("relative_subadults", mod = mod2b_r4, xlevels = list(relative_subadults = seq(0, 100, length.out = 100)))
dat.effects_r16 <- as.data.frame(dat.effects_r16)

p_r16<-ggplot() +
  geom_point(data = metadata_common.species, aes(x = relative_subadults, y = X2bLogical, col = site), shape=19, size=5) +
  geom_ribbon(data = dat.effects_r16, aes(x = relative_subadults, ymin = lower, ymax = upper), alpha = 0.2, fill="lightgrey") +
  geom_line(data = dat.effects_r16, aes(x = relative_subadults, y = fit), size=1) + 
  scale_color_manual(values=c("#008a89", "#8affd8", "#b5004e", "#be9d1f", "#fb9b53"))+
  theme_classic()+ 
  theme(legend.position = c("none")) +
  xlab("Relative Abundance of Subadults")+
  ylab("") +
  ggtitle("")+
  annotate(geom="text", x=3, y=.9, label="F", color="black", size =8)+
  theme(axis.title=element_text(face="bold", size=16), axis.text = element_text(size = 12), axis.text.y=element_blank(), plot.title = element_text(hjust = 0.5, size=22, face="bold"))
p_r16

#Figures main text

Fig3_1<-grid.arrange(p_r1, p_r2, ncol=2, nrow=1)
#export width: 1000, height=500

Fig3_2<-grid.arrange(p_r3, p_r5, p_r7, p_r9, p_r11, p_r13, ncol=2, nrow=3)
Fig3_3<-grid.arrange(p_r4, p_r6, p_r8, p_r10, p_r12, p_r14, ncol=2, nrow=3)
#export width: 500, height=500

Fig3_4<-grid.arrange(p_r15, p_r16, ncol=2, nrow=1)
#export width: 1000, height=500

##Simpson

mod2bSi_r<-glmer(X2bLogical~ INVSIMP + RelAbundHipAb + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSi_r)
summary(mod2bSi_r)
tab_model(mod2bSi_r)
dredge_mod2bSi_r<-dredge(mod2bSi_r)
#summary(model.avg(dredge_mod2bSi_r, subset = delta <= 2))

mod2bSi_r2<-glmer(X2bLogical~ INVSIMP + RelAbundHipB + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSi_r2)
summary(mod2bSi_r2)
tab_model(mod2bSi_r2)
dredge_mod2bSi_r2<-dredge(mod2bSi_r2)
#summary(model.avg(dredge_mod2bSi_r2, subset = delta <= 2))

mod2bSi_r3<-glmer(X2bLogical~ INVSIMP + RelAbundHipC + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSi_r3)
summary(mod2bSi_r3)
tab_model(mod2bSi_r3)
dredge_mod2bSi_r3<-dredge(mod2bSi_r3)
#summary(model.avg(dredge_mod2bSi_r3, subset = delta <= 2))

mod2bSi_r4<-glmer(X2bLogical~ INVSIMP + RelAbundHipD + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSi_r4)
summary(mod2bSi_r4)
tab_model(mod2bSi_r4)
dredge_mod2bSi_r4<-dredge(mod2bSi_r4)
#summary(model.avg(dredge_mod2bSi_r4, subset = delta <= 2))

mod2bSi_r5<-glmer(X2bLogical~ INVSIMP + RelAbundColAf + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSi_r5)
summary(mod2bSi_r5)
tab_model(mod2bSi_r5)
dredge_mod2bSi_r5<-dredge(mod2bSi_r5)
#summary(model.avg(dredge_mod2bSi_r5, subset = delta <= 2))

mod2bSi_r6<-glmer(X2bLogical~ INVSIMP + RelAbundNyc + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSi_r6)
summary(mod2bSi_r6)
tab_model(mod2bSi_r6)
dredge_mod2bSi_r6<-dredge(mod2bSi_r6)
#summary(model.avg(dredge_mod2bSi_r6, subset = delta <= 2))

#FDR correction

p_2b_Si<-c(6.67e-10, 1.22e-06, 1.3e-08, 0.00113, 8.98e-07, 1.17e-06)
p.adjust(p_2b_Si, method="fdr", n=length(p_2b_Si))

p_2b_Abund_Si<-c(0.001, 0.685, 0.287, 3.94e-09, 0.819, 0.014)
p.adjust(p_2b_Abund_Si, method="fdr", n=length(p_2b_Abund_Si))

p_2b_SA_Si<-c(0.002, 0.000859, 0.000548, 0.01509, 0.000798, 0.00138)
p.adjust(p_2b_SA_Si, method="fdr", n=length(p_2b_SA_Si))

##Species Richness

mod2bSR_r<-glmer(X2bLogical~ SR + RelAbundHipAb + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSR_r)
summary(mod2bSR_r)
tab_model(mod2bSR_r)
dredge_mod2bSR_r<-dredge(mod2bSR_r)
#summary(model.avg(dredge_mod2bSR_r, subset = delta <= 2))

mod2bSR_r2<-glmer(X2bLogical~ SR + RelAbundHipB + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSR_r2)
summary(mod2bSR_r2)
tab_model(mod2bSR_r2)
dredge_mod2bSR_r2<-dredge(mod2bSR_r2)
#summary(model.avg(dredge_mod2bSR_r2, subset = delta <= 2))

mod2bSR_r3<-glmer(X2bLogical~ SR + RelAbundHipC + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSR_r3)
summary(mod2bSR_r3)
tab_model(mod2bSR_r3)
dredge_mod2bSR_r3<-dredge(mod2bSR_r3)
#summary(model.avg(dredge_mod2bSR_r3, subset = delta <= 2))

mod2bSR_r4<-glmer(X2bLogical~ SR + RelAbundHipD + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSR_r4)
summary(mod2bSR_r4)
tab_model(mod2bSR_r4)
dredge_mod2bSR_r4<-dredge(mod2bSR_r4)
#summary(model.avg(dredge_mod2bSR_r4, subset = delta <= 2))

mod2bSR_r5<-glmer(X2bLogical~ SR + RelAbundColAf + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSR_r5)
summary(mod2bSR_r5)
tab_model(mod2bSR_r5)
dredge_mod2bSR_r5<-dredge(mod2bSR_r5)
#summary(model.avg(dredge_mod2bSR_r5, subset = delta <= 2))

mod2bSR_r6<-glmer(X2bLogical~ SR + RelAbundNyc + relative_subadults + (1|site/sample_period), family = binomial, data = metadata_common.species, na.action=na.fail)
check_collinearity(mod2bSR_r6)
summary(mod2bSR_r6)
tab_model(mod2bSR_r6)
dredge_mod2bSR_r6<-dredge(mod2bSR_r6)
#summary(model.avg(dredge_mod2bSR_r6, subset = delta <= 2))

#FDR correction

p_2b_SR<-c(0.006, 0.027, 0.017, 0.208, 0.028, 0.147)
p.adjust(p_2b_SR, method="fdr", n=length(p_2b_SR))

p_2b_Abund_SR<-c(0.081, 0.078, 0.836, 1.09e-12, 0.088, 0.004)
p.adjust(p_2b_Abund_SR, method="fdr", n=length(p_2b_Abund_SR))

p_2b_SA_SR<-c(0.000146, 0.000161, 9.17e-05, 0.010, 0.000202, 0.000965)
p.adjust(p_2b_SA_SR, method="fdr", n=length(p_2b_SA_SR))

```

```{r}
###Viral shedding differences

##CoV 229E-like

age_dist_colors<-c("Adult"="#7e365b","Subadult"="#DD7373")
subset_age<-subset(Meyer_Schmid_Dataset_GhanaBats, age!="NA")
X229Epos<-subset(subset_age, X229ELogical=="1")
X2bpos<-subset(subset_age, X2bLogical=="1")

v1<-ggplot(X229Epos, aes(x = age, y=X229Elike)) +
    geom_boxplot(aes(fill=age), size=1) +theme_classic()+
  geom_jitter(aes(fill= age), color="black", size=5, width=0.15, shape=21)+
  scale_color_manual(values=c("#7e365b", "#DD7373"))+
     ylab("Ct Value")+  scale_fill_manual(values = age_dist_colors)+
  xlab("") +ggtitle("")+
  theme_bw() +
  ggtitle("")+
  annotate(geom="text", x=0.5, y=40, label="C", color="black", size =8)+
  theme(plot.title = element_text(hjust = 0.5, size = 25, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 20),
        legend.position='none',
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        text = element_text(colour = "black", size=20),
        axis.text = element_text(colour = "black", size=12),
        axis.text.x = element_text(size=20, vjust = 0.5))
v1


v1.1<-lm(X229Elike ~ age, family = gaussian, data = X229Epos, na.action=na.fail)
summary(v1.1)
summary(aov(X229Epos$X229Elike~X229Epos$age))
t.test(X229Epos$X229Elike~X229Epos$age)
sd(X229Epos$X229Elike[X229Epos$age=="Subadult"])
sd(X229Epos$X229Elike[X229Epos$age=="Adult"])

## CoV 2b

v2<-ggplot(X2bpos, aes(x = age, y=X2b)) +
    geom_boxplot(aes(fill=age), size=1) +theme_classic()+
  geom_jitter(aes(fill= age), color="black", size=5, width=0.15, shape=21)+
  scale_color_manual(values=c("#7e365b", "#DD7373"))+
     ylab("")+  scale_fill_manual(values = age_dist_colors)+
  xlab("") +ggtitle("")+
  theme_bw() +
  ggtitle("")+
  annotate(geom="text", x=0.5, y=40, label="D", color="black", size =8)+
  theme(plot.title = element_text(hjust = 0.5, size = 25, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 20),
        legend.position='none',
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        text = element_text(colour = "black", size=20),
        axis.text = element_text(colour = "black", size=12),
        axis.text.x = element_text(size=20, vjust = 0.5), axis.text.y=element_blank())
v2

t.test(X2bpos$X2b~X2bpos$age)
sd(X2bpos$X2b[X2bpos$age=="Subadult"])
sd(X2bpos$X2b[X2bpos$age=="Adult"])

#Figures Supplementary Material

FigS3<-grid.arrange(v1, v2, ncol=2)
FigS3
#export width: 1000, height=500


#species

subset_species<-subset(Meyer_Schmid_Dataset_GhanaBats, Genus=="Hipposideros")
X229Epos1<-subset(subset_species, X229ELogical=="1")
X2bpos1<-subset(subset_species, X2bLogical=="1")

#CoV 229E-like

s1<-ggplot(X229Epos1, aes(x = Species, y=X229Elike)) +
    geom_boxplot(aes(fill=Species), size=1) +theme_classic()+
  geom_jitter(aes(fill= Species), color="black", size=5, width=0.15, shape=21)+
     ylab("Ct Value")+  scale_fill_manual(values = species_dist_colors)+
  xlab("") +ggtitle("")+
  theme_bw() +
  ggtitle("alpha-CoV 229E-like")+
  annotate(geom="text", x=0.65, y=40, label="A", color="black", size =8)+
  theme(plot.title = element_text(hjust = 0.5, size = 25, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 20),
        legend.position='none',
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        text = element_text(colour = "black", size=20),
        axis.text = element_text(colour = "black", size=12),
        axis.text.x = element_text(size=20, vjust = 0.5, face="italic"))+
  scale_x_discrete(labels = c("H. abae", "H. caffer B", "H. caffer C", "H. caffer D"))
s1

summary(aov(X229Epos1$X229Elike~X229Epos1$Species))

# CoV 2b

s2<-ggplot(X2bpos1, aes(x = Species, y=X2b)) +
    geom_boxplot(aes(fill=Species), size=1) +theme_classic()+
  geom_jitter(aes(fill= Species), color="black", size=5, width=0.15, shape=21)+
     ylab("")+  scale_fill_manual(values = species_dist_colors)+
  xlab("") +ggtitle("")+
  theme_bw() +
  ggtitle("beta-CoV 2b")+
  annotate(geom="text", x=0.65, y=40, label="B", color="black", size =8)+
  theme(plot.title = element_text(hjust = 0.5, size = 25, face = "bold"),
        legend.title = element_blank(),
        legend.text = element_text(size = 20),
        legend.position='none',
        axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        text = element_text(colour = "black", size=20),
        axis.text = element_text(colour = "black", size=12),
        axis.text.x = element_text(size=20, vjust = 0.5, face="italic"), axis.text.y=element_blank())+
  scale_x_discrete(labels = c("H. abae", "H. caffer B", "H. caffer C", "H. caffer D", "H. jonesi", "M. gigas"))
s2

summary(aov(X2bpos1$X2b~X2bpos1$Species))

FigS2_rev<-grid.arrange(s1, s2, v1, v2, ncol=2, nrow=2)

FigS2_rev

###export width: 1700 height: 1000
```

